owner: STEMMechanics
repo: upptime

sites:
  - name: STEMMechanics Website
    url: https://www.stemmechanics.com.au
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/icon-webpage.png
  - name: STEMMechanics Database
    check: "tcp-ping"
    url: db.stemmechanics.com.au
    port: 3306
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/icon-server.png
  - name: Drustcraft Server
    check: "tcp-ping"
    url: play.drustcraft.com.au
    port: 25565
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/icon-minecraft.png
  - name: Drustcraft Website
    url: https://www.drustcraft.com.au
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/icon-webpage.png
  - name: Drustcraft API
    url: https://api.drustcraft.com.au
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/icon-gears.png
  - name: Drustcraft Map
    url: https://map.drustcraft.com.au
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/icon-map.png

status-website:
  cname: status.stemmechanics.com.au
  logoUrl: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/stemmechanics_logo.png
  name: STEMMechanics
  introTitle: "Service Status"
  introMessage: ""
  css: "nav .logo div {display: none;} footer p {font-size: 0.8rem;}"
  navbar:
    - title: Home
      href: https://www.stemmechanics.com.au/
    - title: Status
      href: /
  js: "target=document.querySelector('main');const observer=new MutationObserver(function(){if(document.querySelector('section.live-status')){var a='';document.querySelectorAll('article').forEach(b=>{(ref=b.querySelector('a'))&&(groupIndex=(title=ref.innerHTML).substring(0,title.indexOf(' ')),ref.innerHTML=title.substring(title.indexOf(' ')+1),0!=a.localeCompare(groupIndex)&&(a=groupIndex,(groupElem=document.createElement('h3')).innerHTML=a,(parent=b.parentNode).insertBefore(groupElem,b)))})}});observer.observe(target, {childList:true});"

i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
