owner: STEMMechanics
repo: upptime

sites:
  - name: STEMMechanics Website
    url: https://www.stemmechanics.com.au
  - name: Drustcraft Server
    check: "tcp-ping"
    url: play.drustcraft.com.au
    port: 25565
  - name: Drustcraft Website
    url: https://www.drustcraft.com.au
  - name: Drustcraft API
    url: https://api.drustcraft.com.au
  - name: Drustcraft Map
    url: https://map.drustcraft.com.au

status-website:
  cname: status.stemmechanics.com.au
  logoUrl: https://raw.githubusercontent.com/STEMMechanics/upptime/master/assets/stemmechanics_logo.png
  name: STEMMechanics
  introTitle: "Service Status"
  introMessage: ""
  css: "nav .logo div {display: none;} footer p {font-size: 0.8rem;}"
  navbar:
    - title: Home
      href: https://www.stemmechanics.com.au/
    - title: Status
      href: /
i18n:
  footer: This page is powered by [Upptime](https://upptime.js.org)
