# Change these first
owner: stemmechanics # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - nomadjimbob

sites:
  - name: Website
    url: https://www.stemmechanics.com.au
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/static/server.png
  - name: Database
    url: db.stemmechanics.com.au
    port: $DB_PORT
    check: "tcp-ping"
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/static/server.png
  - name: Minecraft
    url: minecraft.stemmechanics.com.au
    port: 25565
    check: "tcp-ping"
    https://raw.githubusercontent.com/STEMMechanics/upptime/master/static/minecraft.png
  - name: GW-EDM-01
    url: https://gw-edm-01.stemmechanics.com.au
    icon: https://raw.githubusercontent.com/STEMMechanics/upptime/master/static/cloud.png
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stemmechanics.com.au
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/STEMMechanics/upptime/master/static/logo.svg
  name: ""
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.stemmechanics.com.au
    - title: GitHub
      href: https://github.com/$OWNER

i18n:
  footer: Powered by [Upptime](https://upptime.js.org) | Contact us at admin@stemmechanics.com.au

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
